# Env manifest for .env.local — committed, holds NO secret values.
# The real file is .env.local (git-ignored, the source of truth). Secret keys
# are listed blank; config values are inline. Check drift with:
#     ~/.agents/bin/env-check
# Back the real file up / get it back with env-backup and env-restore.
# Generated by env-adopt.
NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
DEVELOPMENT_API_BASE_URL=http://localhost:3001
EFORMSIGN_WEBHOOK_SECRET=
NEXT_PUBLIC_E2E_TEST=
E2E_USER_ID=
E2E_ORG_ID=
OPENAI_API_KEY=

# Optional local-only automatic login. Never set these on a deployment.
LOCAL_AUTO_LOGIN_EMAIL=
LOCAL_AUTO_LOGIN_PASSWORD=
