import { serverAPIClient } from "@/lib/api/server";
import {
    COOKIE_NAMES,
    NO_STORE_CACHE_CONTROL,
    type ParsedBody,
    type ProxyBodyOptions,
    backendJsonResponse,
    createRouteUtils,
    getAccessToken,
    getAuthHeaders,
    getAuthToken,
    getRefreshToken,
    getUpstreamErrorStatus,
    invalidJsonResponse,
    logUpstreamError,
    parseBody,
    readJsonObjectBody,
    sanitizeUpstreamClientError,
    unauthorizedResponse,
    upstreamJsonErrorResponse,
    upstreamSseErrorResponse,
    upstreamStreamErrorResponse,
    upstreamStreamTransportErrorResponse,
    withNoStore,
} from "@babyjamjam/shared/api";

const {
    errorResponse,
    proxyDeleteRequest,
    proxyGetRequest,
    proxyLocalGetRequest,
    proxyPostRequest,
    setAuthCookies,
} = createRouteUtils({
    errorResponseMode: "legacy-message",
    secureCookies: process.env.NODE_ENV === "production",
    serverAPIClient,
});

export {
    COOKIE_NAMES,
    NO_STORE_CACHE_CONTROL,
    type ParsedBody,
    type ProxyBodyOptions,
    backendJsonResponse,
    errorResponse,
    getAccessToken,
    getAuthHeaders,
    getAuthToken,
    getRefreshToken,
    getUpstreamErrorStatus,
    invalidJsonResponse,
    logUpstreamError,
    parseBody,
    proxyDeleteRequest,
    proxyGetRequest,
    proxyLocalGetRequest,
    proxyPostRequest,
    readJsonObjectBody,
    sanitizeUpstreamClientError,
    setAuthCookies,
    unauthorizedResponse,
    upstreamJsonErrorResponse,
    upstreamSseErrorResponse,
    upstreamStreamErrorResponse,
    upstreamStreamTransportErrorResponse,
    withNoStore,
};
