# Env manifest for .env — committed, holds NO secret values.
# The real file is .env (git-ignored, the source of truth). Secret keys
# are listed blank; config values are inline. Check drift with:
#     ~/.agents/bin/env-check
# Back the real file up / get it back with env-backup and env-restore.
# Generated by env-adopt.
# backend/env.tpl — rendered by: ~/.agents/bin/env-pull backend/env.tpl
# References only, never secret material. Safe to commit.
# Note: the renderer parses comments too, so never write a reference
# prefix in prose here — it is treated as a real reference.

DATABASE_URL=
DIRECT_URL=
# Database route selected at startup: shared uses DATABASE_URL; direct uses DIRECT_URL.
DATABASE_CONNECTION_MODE="shared"
# Tenant-isolation Prisma extension enforcement level: off | observe | enforce. Default observe.
TENANT_ISOLATION_MODE="observe"
JWT_SECRET=
KAKAO_CLIENT_ID="479afcedc0c97cded2033bfbfb4472ee"
KAKAO_CLIENT_SECRET=
KAKAO_CALLBACK_URL=http://localhost:3001/auth/kakao/callback
NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
DEVELOPMENT_API_BASE_URL=http://localhost:3001
DEVELOPMENT_FRONTEND_URL=http://localhost:3000
DEVELOPMENT_MOBILE_FRONTEND_URL=http://localhost:3002
PRODUCTION_FRONTEND_URL="https://admin.babyjamjam.com"
PRODUCTION_MOBILE_FRONTEND_URL="https://m.admin.babyjamjam.com"
PREVIEW_FRONTEND_URL="https://staff.babyjamjam.com"
SUPABASE_URL="https://ebiughoiebblasxwgxbe.supabase.co"
SUPABASE_SERVICE_KEY=
GEMINI_API_KEY=
GEMINI_CHAT_MODEL=
GEMINI_CHAT_TEMPERATURE=
GEMINI_CHAT_MAX_OUTPUT_TOKENS=
GEMINI_CHAT_TIMEOUT_MS=
GEMINI_EXTRACTION_MODEL=
EFORMSIGN_USER_EMAIL="forchildrenbysongs@gmail.com"
EFORMSIGN_API_URL="https://api.eformsign.com"
EFORMSIGN_DOC_API_URL="https://kr-api.eformsign.com"
EFORMSIGN_API_KEY=
EFORMSIGN_PRIVATE_KEY=
EFORMSIGN_COMPANY_ID="6635b9dacdbc4837ba378c6336ef1e34"
EFORMSIGN_TEMPLATE_ID="d1591da29590495d800f55f1d1fc1378"
EFORMSIGN_FEEDBACK_TEMPLATE_ID="f091d768fb2c4a74b429525b428337f7"
EFORMSIGN_FEEDBACK_TEMPLATE_ID_10="0dca5a5ace7d47e6a911c6bfa3103534"
EFORMSIGN_FEEDBACK_TEMPLATE_ID_15="acc55dd658c6489f80e64bb3d3970140"
EFORMSIGN_FEEDBACK_TEMPLATE_ID_20="7522d1e4786748068dc3a93e0bfb081a"
EFORMSIGN_WEBHOOK_SECRET=
# The 6-hourly eformsign mirror sweep (webhook safety net behind auto client
# registration) requires a cross-instance lock from VALKEY_URL. This deployment
# runs a single backend replica, so approve the in-process lock instead of
# leaving the sweep permanently skipped.
EFORMSIGN_RECONCILE_ALLOW_UNLOCKED="true"
# Host-level scheduler lease (ADR-010). The LightNode fallback pins `required`
# and holder `lightnode` in its Compose files; Lightsail gets `lightsail` in its
# host backend.env as a BJJ-298 failback step and until then defaults to
# `required` with the container hostname as holder. Local development runs
# `off` so a laptop can never take the production lease.
SCHEDULER_LEASE_MODE="off"
SCHEDULER_LEASE_HOLDER_ID="local"
ALIGO_API_URL="https://kakaoapi.aligo.in"
ALIGO_API_KEY=
ALIGO_USER_ID="forchildrenbys"
ALIGO_SENDER_KEY=
ALIGO_SENDER_PHONE="010-9641-1878"
CHANNELTALK_API_URL="https://api.channel.io"
CHANNELTALK_ACCESS_KEY=
CHANNELTALK_ACCESS_SECRET=
VAPID_PUBLIC_KEY="BLbY845TlJyGq4F8-7ezddfhd_uzVTBFXc1XZ2mSDPXISPzlh7JdgWzlrfL1xbgLBIXa_AYuFwncj8CdS5BNfsQ"
VAPID_PRIVATE_KEY=
VAPID_EMAIL="forchildrenbysongs@gmail.com"
RESEND_API_KEY=
RESEND_FROM_EMAIL=admin@babyjamjam.com

# Local-only service record testing. Fallback only — `pnpm start:dev` auto-resolves the current LAN IP and overrides this (scripts/start-dev-lan.mjs).
MOBILE_SERVICE_RECORD_BASE_URL="http://192.168.219.142:3002"
# 영수증 링크 베이스 URL (m.admin). 비우면 MOBILE_SERVICE_RECORD_BASE_URL → https://m.admin.babyjamjam.com 순으로 폴백
MOBILE_RECEIPT_BASE_URL="http://192.168.219.142:3002"
# 생년월일 해시 솔트 (비밀값)
RECEIPT_LINK_HASH_SALT=
SERVICE_RECORD_AUTO_FINALIZE_ENABLED=true
EFORMSIGN_SERVICE_RECORD_TEMPLATE_ID="f091d768fb2c4a74b429525b428337f7"
EFORMSIGN_SERVICE_RECORD_TEMPLATE_ID_10="0dca5a5ace7d47e6a911c6bfa3103534"
EFORMSIGN_SERVICE_RECORD_TEMPLATE_ID_15="acc55dd658c6489f80e64bb3d3970140"
EFORMSIGN_SERVICE_RECORD_TEMPLATE_ID_20="7522d1e4786748068dc3a93e0bfb081a"
