import { serverAPIClient } from "@/lib/api/server";
import { getServerRuntimeConfig } from "@/lib/env";
import {
    NO_STORE_CACHE_CONTROL,
    type ParsedBody,
    type ProxyBodyOptions,
    backendJsonResponse,
    createRouteUtils,
    getAuthHeaders,
    getAuthToken,
    getUpstreamErrorStatus,
    invalidJsonResponse,
    logUpstreamError,
    parseBody,
    readJsonObjectBody,
    sanitizeUpstreamClientError,
    unauthorizedResponse,
    upstreamJsonErrorResponse,
    upstreamSseErrorResponse,
    upstreamStreamErrorResponse,
    upstreamStreamTransportErrorResponse,
    withNoStore,
} from "@babyjamjam/shared/api";

const {
    errorResponse,
    proxyDeleteRequest,
    proxyGetRequest,
    proxyLocalGetRequest,
    proxyPostRequest,
} = createRouteUtils({
    secureCookies: getServerRuntimeConfig().isProductionNodeEnv,
    serverAPIClient,
});

export {
    NO_STORE_CACHE_CONTROL,
    type ParsedBody,
    type ProxyBodyOptions,
    backendJsonResponse,
    errorResponse,
    getAuthHeaders,
    getAuthToken,
    getUpstreamErrorStatus,
    invalidJsonResponse,
    logUpstreamError,
    parseBody,
    proxyDeleteRequest,
    proxyGetRequest,
    proxyLocalGetRequest,
    proxyPostRequest,
    readJsonObjectBody,
    sanitizeUpstreamClientError,
    unauthorizedResponse,
    upstreamJsonErrorResponse,
    upstreamSseErrorResponse,
    upstreamStreamErrorResponse,
    upstreamStreamTransportErrorResponse,
    withNoStore,
};
