export const NOTIFICATION_EMAIL_ENABLED =
    process.env.NEXT_PUBLIC_NOTIFICATION_EMAIL_ENABLED === "true";

export const PWA_NOTIFICATIONS_ENABLED =
    process.env.NEXT_PUBLIC_PWA_NOTIFICATIONS_ENABLED === "true";
